server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dentist_hunt
    username: postgres
    password: Abdullah2004*
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
springdoc:
  paths-to-match: /**